// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportEntry.proto

package fanjh.mine.buriedpoint.pb;

public final class ReportEntry {
  private ReportEntry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fanjh.mine.buriedpoint.pb.Report)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    java.util.List<Report.Entry>
        getArraysList();
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    Report.Entry getArrays(int index);
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    int getArraysCount();
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    java.util.List<? extends Report.EntryOrBuilder>
        getArraysOrBuilderList();
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    Report.EntryOrBuilder getArraysOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code fanjh.mine.buriedpoint.pb.Report}
   */
  public  static final class Report extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fanjh.mine.buriedpoint.pb.Report)
      ReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Report.newBuilder() to construct.
    private Report(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Report() {
      arrays_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Report(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                arrays_ = new java.util.ArrayList<Entry>();
                mutable_bitField0_ |= 0x00000001;
              }
              arrays_.add(
                  input.readMessage(Entry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          arrays_ = java.util.Collections.unmodifiableList(arrays_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.class, Builder.class);
    }

    public interface EntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fanjh.mine.buriedpoint.pb.Report.Entry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string lib = 1;</code>
       */
      String getLib();
      /**
       * <code>string lib = 1;</code>
       */
      com.google.protobuf.ByteString
          getLibBytes();

      /**
       * <code>string user = 2;</code>
       */
      String getUser();
      /**
       * <code>string user = 2;</code>
       */
      com.google.protobuf.ByteString
          getUserBytes();

      /**
       * <code>string common = 3;</code>
       */
      String getCommon();
      /**
       * <code>string common = 3;</code>
       */
      com.google.protobuf.ByteString
          getCommonBytes();

      /**
       * <code>string eventname = 4;</code>
       */
      String getEventname();
      /**
       * <code>string eventname = 4;</code>
       */
      com.google.protobuf.ByteString
          getEventnameBytes();

      /**
       * <code>sint64 time = 5;</code>
       */
      long getTime();
    }
    /**
     * Protobuf type {@code fanjh.mine.buriedpoint.pb.Report.Entry}
     */
    public  static final class Entry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:fanjh.mine.buriedpoint.pb.Report.Entry)
        EntryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Entry.newBuilder() to construct.
      private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Entry() {
        lib_ = "";
        user_ = "";
        common_ = "";
        eventname_ = "";
        time_ = 0L;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Entry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                lib_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                user_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                common_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                eventname_ = s;
                break;
              }
              case 40: {

                time_ = input.readSInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Entry.class, Builder.class);
      }

      public static final int LIB_FIELD_NUMBER = 1;
      private volatile Object lib_;
      /**
       * <code>string lib = 1;</code>
       */
      public String getLib() {
        Object ref = lib_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          lib_ = s;
          return s;
        }
      }
      /**
       * <code>string lib = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLibBytes() {
        Object ref = lib_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          lib_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int USER_FIELD_NUMBER = 2;
      private volatile Object user_;
      /**
       * <code>string user = 2;</code>
       */
      public String getUser() {
        Object ref = user_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          user_ = s;
          return s;
        }
      }
      /**
       * <code>string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int COMMON_FIELD_NUMBER = 3;
      private volatile Object common_;
      /**
       * <code>string common = 3;</code>
       */
      public String getCommon() {
        Object ref = common_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          common_ = s;
          return s;
        }
      }
      /**
       * <code>string common = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommonBytes() {
        Object ref = common_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          common_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EVENTNAME_FIELD_NUMBER = 4;
      private volatile Object eventname_;
      /**
       * <code>string eventname = 4;</code>
       */
      public String getEventname() {
        Object ref = eventname_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          eventname_ = s;
          return s;
        }
      }
      /**
       * <code>string eventname = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEventnameBytes() {
        Object ref = eventname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eventname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TIME_FIELD_NUMBER = 5;
      private long time_;
      /**
       * <code>sint64 time = 5;</code>
       */
      public long getTime() {
        return time_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getLibBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lib_);
        }
        if (!getUserBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
        }
        if (!getCommonBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, common_);
        }
        if (!getEventnameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eventname_);
        }
        if (time_ != 0L) {
          output.writeSInt64(5, time_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getLibBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lib_);
        }
        if (!getUserBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
        }
        if (!getCommonBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, common_);
        }
        if (!getEventnameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eventname_);
        }
        if (time_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt64Size(5, time_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Entry)) {
          return super.equals(obj);
        }
        Entry other = (Entry) obj;

        boolean result = true;
        result = result && getLib()
            .equals(other.getLib());
        result = result && getUser()
            .equals(other.getUser());
        result = result && getCommon()
            .equals(other.getCommon());
        result = result && getEventname()
            .equals(other.getEventname());
        result = result && (getTime()
            == other.getTime());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LIB_FIELD_NUMBER;
        hash = (53 * hash) + getLib().hashCode();
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
        hash = (37 * hash) + COMMON_FIELD_NUMBER;
        hash = (53 * hash) + getCommon().hashCode();
        hash = (37 * hash) + EVENTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getEventname().hashCode();
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Entry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Entry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Entry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Entry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Entry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Entry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Entry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Entry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Entry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Entry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Entry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Entry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Entry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code fanjh.mine.buriedpoint.pb.Report.Entry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:fanjh.mine.buriedpoint.pb.Report.Entry)
          EntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Entry.class, Builder.class);
        }

        // Construct using fanjh.mine.buriedpoint.pb.ReportEntry.Report.Entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          lib_ = "";

          user_ = "";

          common_ = "";

          eventname_ = "";

          time_ = 0L;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_descriptor;
        }

        public Entry getDefaultInstanceForType() {
          return Entry.getDefaultInstance();
        }

        public Entry build() {
          Entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Entry buildPartial() {
          Entry result = new Entry(this);
          result.lib_ = lib_;
          result.user_ = user_;
          result.common_ = common_;
          result.eventname_ = eventname_;
          result.time_ = time_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Entry) {
            return mergeFrom((Entry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Entry other) {
          if (other == Entry.getDefaultInstance()) return this;
          if (!other.getLib().isEmpty()) {
            lib_ = other.lib_;
            onChanged();
          }
          if (!other.getUser().isEmpty()) {
            user_ = other.user_;
            onChanged();
          }
          if (!other.getCommon().isEmpty()) {
            common_ = other.common_;
            onChanged();
          }
          if (!other.getEventname().isEmpty()) {
            eventname_ = other.eventname_;
            onChanged();
          }
          if (other.getTime() != 0L) {
            setTime(other.getTime());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Entry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object lib_ = "";
        /**
         * <code>string lib = 1;</code>
         */
        public String getLib() {
          Object ref = lib_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            lib_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string lib = 1;</code>
         */
        public com.google.protobuf.ByteString
            getLibBytes() {
          Object ref = lib_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            lib_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string lib = 1;</code>
         */
        public Builder setLib(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          lib_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string lib = 1;</code>
         */
        public Builder clearLib() {
          
          lib_ = getDefaultInstance().getLib();
          onChanged();
          return this;
        }
        /**
         * <code>string lib = 1;</code>
         */
        public Builder setLibBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          lib_ = value;
          onChanged();
          return this;
        }

        private Object user_ = "";
        /**
         * <code>string user = 2;</code>
         */
        public String getUser() {
          Object ref = user_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            user_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string user = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUserBytes() {
          Object ref = user_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            user_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string user = 2;</code>
         */
        public Builder setUser(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          user_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string user = 2;</code>
         */
        public Builder clearUser() {
          
          user_ = getDefaultInstance().getUser();
          onChanged();
          return this;
        }
        /**
         * <code>string user = 2;</code>
         */
        public Builder setUserBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          user_ = value;
          onChanged();
          return this;
        }

        private Object common_ = "";
        /**
         * <code>string common = 3;</code>
         */
        public String getCommon() {
          Object ref = common_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            common_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string common = 3;</code>
         */
        public com.google.protobuf.ByteString
            getCommonBytes() {
          Object ref = common_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            common_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string common = 3;</code>
         */
        public Builder setCommon(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          common_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string common = 3;</code>
         */
        public Builder clearCommon() {
          
          common_ = getDefaultInstance().getCommon();
          onChanged();
          return this;
        }
        /**
         * <code>string common = 3;</code>
         */
        public Builder setCommonBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          common_ = value;
          onChanged();
          return this;
        }

        private Object eventname_ = "";
        /**
         * <code>string eventname = 4;</code>
         */
        public String getEventname() {
          Object ref = eventname_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            eventname_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string eventname = 4;</code>
         */
        public com.google.protobuf.ByteString
            getEventnameBytes() {
          Object ref = eventname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            eventname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string eventname = 4;</code>
         */
        public Builder setEventname(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          eventname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string eventname = 4;</code>
         */
        public Builder clearEventname() {
          
          eventname_ = getDefaultInstance().getEventname();
          onChanged();
          return this;
        }
        /**
         * <code>string eventname = 4;</code>
         */
        public Builder setEventnameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          eventname_ = value;
          onChanged();
          return this;
        }

        private long time_ ;
        /**
         * <code>sint64 time = 5;</code>
         */
        public long getTime() {
          return time_;
        }
        /**
         * <code>sint64 time = 5;</code>
         */
        public Builder setTime(long value) {
          
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>sint64 time = 5;</code>
         */
        public Builder clearTime() {
          
          time_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:fanjh.mine.buriedpoint.pb.Report.Entry)
      }

      // @@protoc_insertion_point(class_scope:fanjh.mine.buriedpoint.pb.Report.Entry)
      private static final Entry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Entry();
      }

      public static Entry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Entry>
          PARSER = new com.google.protobuf.AbstractParser<Entry>() {
        public Entry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Entry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Entry> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Entry> getParserForType() {
        return PARSER;
      }

      public Entry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ARRAYS_FIELD_NUMBER = 1;
    private java.util.List<Entry> arrays_;
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    public java.util.List<Entry> getArraysList() {
      return arrays_;
    }
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    public java.util.List<? extends EntryOrBuilder>
        getArraysOrBuilderList() {
      return arrays_;
    }
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    public int getArraysCount() {
      return arrays_.size();
    }
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    public Entry getArrays(int index) {
      return arrays_.get(index);
    }
    /**
     * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
     */
    public EntryOrBuilder getArraysOrBuilder(
        int index) {
      return arrays_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < arrays_.size(); i++) {
        output.writeMessage(1, arrays_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < arrays_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, arrays_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Report)) {
        return super.equals(obj);
      }
      Report other = (Report) obj;

      boolean result = true;
      result = result && getArraysList()
          .equals(other.getArraysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArraysCount() > 0) {
        hash = (37 * hash) + ARRAYS_FIELD_NUMBER;
        hash = (53 * hash) + getArraysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Report parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Report parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Report prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fanjh.mine.buriedpoint.pb.Report}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fanjh.mine.buriedpoint.pb.Report)
        ReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.class, Builder.class);
      }

      // Construct using fanjh.mine.buriedpoint.pb.ReportEntry.Report.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArraysFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (arraysBuilder_ == null) {
          arrays_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arraysBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReportEntry.internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor;
      }

      public Report getDefaultInstanceForType() {
        return Report.getDefaultInstance();
      }

      public Report build() {
        Report result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Report buildPartial() {
        Report result = new Report(this);
        int from_bitField0_ = bitField0_;
        if (arraysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            arrays_ = java.util.Collections.unmodifiableList(arrays_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.arrays_ = arrays_;
        } else {
          result.arrays_ = arraysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Report) {
          return mergeFrom((Report)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Report other) {
        if (other == Report.getDefaultInstance()) return this;
        if (arraysBuilder_ == null) {
          if (!other.arrays_.isEmpty()) {
            if (arrays_.isEmpty()) {
              arrays_ = other.arrays_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArraysIsMutable();
              arrays_.addAll(other.arrays_);
            }
            onChanged();
          }
        } else {
          if (!other.arrays_.isEmpty()) {
            if (arraysBuilder_.isEmpty()) {
              arraysBuilder_.dispose();
              arraysBuilder_ = null;
              arrays_ = other.arrays_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arraysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArraysFieldBuilder() : null;
            } else {
              arraysBuilder_.addAllMessages(other.arrays_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Report parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Report) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Entry> arrays_ =
        java.util.Collections.emptyList();
      private void ensureArraysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          arrays_ = new java.util.ArrayList<Entry>(arrays_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Entry, Entry.Builder, EntryOrBuilder> arraysBuilder_;

      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public java.util.List<Entry> getArraysList() {
        if (arraysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arrays_);
        } else {
          return arraysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public int getArraysCount() {
        if (arraysBuilder_ == null) {
          return arrays_.size();
        } else {
          return arraysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Entry getArrays(int index) {
        if (arraysBuilder_ == null) {
          return arrays_.get(index);
        } else {
          return arraysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder setArrays(
          int index, Entry value) {
        if (arraysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArraysIsMutable();
          arrays_.set(index, value);
          onChanged();
        } else {
          arraysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder setArrays(
          int index, Entry.Builder builderForValue) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.set(index, builderForValue.build());
          onChanged();
        } else {
          arraysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder addArrays(Entry value) {
        if (arraysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArraysIsMutable();
          arrays_.add(value);
          onChanged();
        } else {
          arraysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder addArrays(
          int index, Entry value) {
        if (arraysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArraysIsMutable();
          arrays_.add(index, value);
          onChanged();
        } else {
          arraysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder addArrays(
          Entry.Builder builderForValue) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.add(builderForValue.build());
          onChanged();
        } else {
          arraysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder addArrays(
          int index, Entry.Builder builderForValue) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.add(index, builderForValue.build());
          onChanged();
        } else {
          arraysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder addAllArrays(
          Iterable<? extends Entry> values) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arrays_);
          onChanged();
        } else {
          arraysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder clearArrays() {
        if (arraysBuilder_ == null) {
          arrays_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arraysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Builder removeArrays(int index) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.remove(index);
          onChanged();
        } else {
          arraysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Entry.Builder getArraysBuilder(
          int index) {
        return getArraysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public EntryOrBuilder getArraysOrBuilder(
          int index) {
        if (arraysBuilder_ == null) {
          return arrays_.get(index);  } else {
          return arraysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public java.util.List<? extends EntryOrBuilder>
           getArraysOrBuilderList() {
        if (arraysBuilder_ != null) {
          return arraysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arrays_);
        }
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Entry.Builder addArraysBuilder() {
        return getArraysFieldBuilder().addBuilder(
            Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public Entry.Builder addArraysBuilder(
          int index) {
        return getArraysFieldBuilder().addBuilder(
            index, Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .fanjh.mine.buriedpoint.pb.Report.Entry arrays = 1;</code>
       */
      public java.util.List<Entry.Builder>
           getArraysBuilderList() {
        return getArraysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Entry, Entry.Builder, EntryOrBuilder>
          getArraysFieldBuilder() {
        if (arraysBuilder_ == null) {
          arraysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Entry, Entry.Builder, EntryOrBuilder>(
                  arrays_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          arrays_ = null;
        }
        return arraysBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fanjh.mine.buriedpoint.pb.Report)
    }

    // @@protoc_insertion_point(class_scope:fanjh.mine.buriedpoint.pb.Report)
    private static final Report DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Report();
    }

    public static Report getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Report>
        PARSER = new com.google.protobuf.AbstractParser<Report>() {
      public Report parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Report(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Report> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Report> getParserForType() {
      return PARSER;
    }

    public Report getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fanjh_mine_buriedpoint_pb_Report_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021ReportEntry.proto\022\031fanjh.mine.buriedpo" +
      "int.pb\"\226\001\n\006Report\0227\n\006arrays\030\001 \003(\0132\'.fanj" +
      "h.mine.buriedpoint.pb.Report.Entry\032S\n\005En" +
      "try\022\013\n\003lib\030\001 \001(\t\022\014\n\004user\030\002 \001(\t\022\016\n\006common" +
      "\030\003 \001(\t\022\021\n\teventname\030\004 \001(\t\022\014\n\004time\030\005 \001(\022B" +
      "(\n\031fanjh.mine.buriedpoint.pbB\013ReportEntr" +
      "yb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fanjh_mine_buriedpoint_pb_Report_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor,
        new String[] { "Arrays", });
    internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_descriptor =
      internal_static_fanjh_mine_buriedpoint_pb_Report_descriptor.getNestedTypes().get(0);
    internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fanjh_mine_buriedpoint_pb_Report_Entry_descriptor,
        new String[] { "Lib", "User", "Common", "Eventname", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
